# ustawienia domyślne dla logistyki i MRP

# DOMYŚLNA ILOŚC TYGODNIOWA PRODUKCJI AUTOMATÓW 
DEFAULT_WEEKLY_PRODUCTION = 12

# LICZZBA DNI ROBOCZYCH W TYGODNIU 
WORKING_DAYS_PER_WEEK = 5

#DOMYŚLNY ZAPAS BEZPIECZEŃSTWA W MAGAZYNIE W JEDNOSTCE DNI ROBOCZYCH 
SAFETY_STOCK_DAYS = 3

# PRÓG ALARMOWY DLA MOQ (W TYGDONIACH ZAPASU) 
# JEŻLI MOQ DOSTAWCY ZMUSZA NAS DO ZAKUPU NA WIĘCEJ NIŻ 10 TYGODNI -> RED FLAG 
MOQ_ALERT_WEEKS_THRESHOLD = 10 

